apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- ingress.yaml

images:
- name: structarray-search
  newName: harbor-us1.zilliz.cc/uso/milvus3-demos-structarray-search
  newTag: v0.1.0
