"""Fictional e-commerce catalog definition for the Function Chain demo.

This module is the single source of truth for the synthetic catalog. Nothing
here is derived from a real retailer: product identifiers, brand names, titles,
descriptions, and bullet points are all invented for the demo, and every field
is marked ``synthetic`` in the generated provenance.

Layout is kept intentionally compatible with the rest of the pipeline:
- 20 product types, 240 products total. The first 120 rows keep the exact
  intent-curation layout below; an appended expansion pass adds six
  ``catalog_background`` products to every one of the 20 types.
- 6 intent types carry ``strong`` / ``partial`` / ``intra_type_hard_negative``
  labels that a plain reading of the text can explain.
- 14 background types are all ``catalog_background``; the expansion rows are
  also ``catalog_background`` and may appear inside the six intent types.
- Each product carries a deterministic operational profile tier (H/G/S/N/R)
  used only to shape fictional rating/inventory/return/age signals.

``validate()`` asserts the quotas so a typo cannot silently break the pipeline.
"""

from __future__ import annotations

from typing import Final

from function_chain_demo.catalog_curation import (
    BACKGROUND,
    INTRA_TYPE_HARD_NEGATIVE,
    PARTIAL,
    STRONG,
)

CATALOG_VERSION: Final = "synthetic-commerce-catalog-v1"

# Fictional brand names. None of these are real merchants.
BRANDS: Final = (
    "Northline",
    "Haven & Co.",
    "Timbermark",
    "Lumora",
    "Cloudrest",
    "Ironfield",
    "Verdant",
    "Meridian",
    "Solace Living",
    "Apex Gear",
)

# Human-facing display noun per product type, used for a generic node path.
TYPE_DISPLAY: Final[dict[str, str]] = {
    "SOFA": "Sofas",
    "CHAIR": "Chairs",
    "TABLE": "Tables",
    "LAMP": "Lighting",
    "RUG": "Rugs",
    "HANDBAG": "Bags",
    "BACKPACK": "Backpacks",
    "SHOES": "Shoes",
    "BOOT": "Boots",
    "SANDAL": "Sandals",
    "HAT": "Hats",
    "SUITCASE": "Luggage",
    "HEADPHONES": "Headphones",
    "DRINKING_CUP": "Drinkware",
    "PILLOW": "Pillows",
    "BED": "Beds",
    "SHELF": "Shelving",
    "DESK": "Desks",
    "PLANTER": "Planters",
    "UMBRELLA": "Umbrellas",
}


def _row(
    product_type: str,
    label: str,
    profile: str,
    brand: str,
    title: str,
    color: str,
    material: str,
    style: str,
    description: str,
    bullet_points: tuple[str, ...],
    reason: str,
) -> dict[str, object]:
    return {
        "product_type": product_type,
        "selection_class": label,
        "profile": profile,
        "brand": brand,
        "title": title,
        "color": color,
        "material": material,
        "style": style,
        "description": description,
        "bullet_points": bullet_points,
        "selection_reason": reason,
    }


# ---------------------------------------------------------------------------
# Intent types: strong (fully matches), partial (modifier mismatch),
# intra_type_hard_negative (same-type but disqualifying use/form/color).
# ---------------------------------------------------------------------------

_DESK: Final = (
    _row(
        "DESK",
        STRONG,
        "H",
        "Timbermark",
        "Timbermark Compact Dark Walnut Writing Desk, 100 x 50 cm",
        "Dark Walnut",
        "Engineered wood",
        "Modern",
        "A space-conscious writing desk with a dark walnut wood-look finish for a small home office.",
        (
            "Compact 100 x 50 cm footprint fits a small office",
            "Dark walnut wood-look finish",
            "One cable-routing cutout",
        ),
        "compact desk with a visibly dark wood or wood-look finish",
    ),
    _row(
        "DESK",
        STRONG,
        "G",
        "Timbermark",
        "Timbermark Compact Espresso Desk with Storage Shelf, 110 x 55 cm",
        "Espresso",
        "MDF",
        "Contemporary",
        "A compact espresso-finished desk with a lower storage shelf for tight home-office corners.",
        ("Espresso dark-wood finish", "Open lower storage shelf", "Compact 110 x 55 cm top"),
        "compact desk with a dark espresso wood finish",
    ),
    _row(
        "DESK",
        STRONG,
        "G",
        "Haven & Co.",
        "Haven & Co. Foldable Walnut Laptop Desk, 90 x 45 cm",
        "Walnut",
        "Wood veneer",
        "Minimal",
        "A foldable walnut-veneer laptop desk that tucks away when not in use.",
        ("Foldable for easy storage", "Walnut veneer top", "90 x 45 cm work surface"),
        "compact foldable desk with a walnut finish",
    ),
    _row(
        "DESK",
        STRONG,
        "S",
        "Haven & Co.",
        "Haven & Co. Compact Chestnut Study Desk, 105 x 50 cm",
        "Chestnut",
        "Particle board",
        "Modern",
        "A compact chestnut study desk sized for small bedrooms and studio apartments.",
        ("Chestnut wood-look finish", "Compact 105 x 50 cm top", "Tool-free assembly"),
        "compact desk with a dark chestnut finish",
    ),
    _row(
        "DESK",
        STRONG,
        "S",
        "Northline",
        "Northline Space-Saving Black Oak Desk, 95 x 48 cm",
        "Black",
        "Oak-effect laminate",
        "Contemporary",
        "A space-saving desk in a black oak-effect laminate for compact work areas.",
        ("Space-saving 95 x 48 cm top", "Black oak-effect finish", "Sturdy steel legs"),
        "compact desk with a dark black wood-look finish",
    ),
    _row(
        "DESK",
        STRONG,
        "N",
        "Northline",
        "Northline Compact Dark Brown Desk with Drawer, 115 x 55 cm",
        "Dark Brown",
        "MDF",
        "Classic",
        "A compact dark-brown desk with a single utility drawer for a small office.",
        ("Dark brown finish", "Single utility drawer", "Compact 115 x 55 cm top"),
        "compact desk with a dark brown finish",
    ),
    _row(
        "DESK",
        PARTIAL,
        "N",
        "Timbermark",
        "Timbermark Compact White Writing Desk, 100 x 50 cm",
        "White",
        "MDF",
        "Modern",
        "A compact writing desk in a bright white finish for small spaces.",
        ("Compact 100 x 50 cm top", "Bright white finish", "Minimal frame"),
        "compact desk with an explicit finish mismatch (white)",
    ),
    _row(
        "DESK",
        INTRA_TYPE_HARD_NEGATIVE,
        "R",
        "Apex Gear",
        "Apex Gear RGB Gaming Desk with L-Shaped Corner, 140 cm",
        "Black",
        "Steel and MDF",
        "Gaming",
        "An L-shaped gaming desk with RGB trim built for large multi-monitor setups.",
        ("L-shaped corner layout", "RGB edge lighting", "Built-in headphone hook"),
        "gaming L-shaped desk conflicts with the compact dark-wood intent",
    ),
)

_RUG: Final = (
    _row(
        "RUG",
        STRONG,
        "H",
        "Solace Living",
        "Solace Living Plush Ivory Area Rug, 160 x 230 cm",
        "Ivory",
        "Polyester",
        "Casual",
        "A plush ivory area rug that softens a cozy living room.",
        ("Soft plush pile", "Neutral ivory tone", "160 x 230 cm"),
        "rug has an explicit neutral color family",
    ),
    _row(
        "RUG",
        STRONG,
        "G",
        "Solace Living",
        "Solace Living Beige Low-Pile Living Room Rug, 140 x 200 cm",
        "Beige",
        "Wool blend",
        "Transitional",
        "A beige low-pile rug sized for a comfortable living room arrangement.",
        ("Low pile is easy to clean", "Warm beige neutral", "140 x 200 cm"),
        "rug has an explicit neutral color family",
    ),
    _row(
        "RUG",
        STRONG,
        "G",
        "Cloudrest",
        "Cloudrest Cream Shag Rug, 120 x 170 cm",
        "Cream",
        "Synthetic shag",
        "Cozy",
        "A deep cream shag rug for a soft, neutral living-room feel.",
        ("Deep shag pile", "Cream neutral tone", "120 x 170 cm"),
        "rug has an explicit neutral color family",
    ),
    _row(
        "RUG",
        STRONG,
        "S",
        "Cloudrest",
        "Cloudrest Grey Wool Rug, 160 x 230 cm",
        "Grey",
        "Wool",
        "Modern",
        "A grey wool rug that anchors a modern living room without loud color.",
        ("Neutral grey tone", "Natural wool", "160 x 230 cm"),
        "rug has an explicit neutral color family",
    ),
    _row(
        "RUG",
        STRONG,
        "S",
        "Haven & Co.",
        "Haven & Co. Taupe Indoor Rug, 130 x 190 cm",
        "Taupe",
        "Cotton blend",
        "Farmhouse",
        "A taupe cotton-blend rug for a warm, understated living room.",
        ("Neutral taupe tone", "Soft cotton blend", "130 x 190 cm"),
        "rug has an explicit neutral color family",
    ),
    _row(
        "RUG",
        STRONG,
        "N",
        "Haven & Co.",
        "Haven & Co. Natural Jute Rug, 150 x 210 cm",
        "Natural",
        "Jute",
        "Bohemian",
        "A natural jute rug that brings texture without color noise to a living room.",
        ("Natural jute fiber", "Neutral earthy tone", "150 x 210 cm"),
        "rug has an explicit neutral color family",
    ),
    _row(
        "RUG",
        PARTIAL,
        "N",
        "Cloudrest",
        "Cloudrest Ivory and Blue Accent Rug, 140 x 200 cm",
        "Ivory and Blue",
        "Polyester",
        "Contemporary",
        "An ivory rug with a visible blue border accent for a living room.",
        ("Neutral ivory base", "Visible blue border accent", "140 x 200 cm"),
        "neutral base with a visible non-neutral blue accent",
    ),
    _row(
        "RUG",
        INTRA_TYPE_HARD_NEGATIVE,
        "R",
        "Verdant",
        "Verdant Vibrant Red Living Room Rug, 160 x 230 cm",
        "Red",
        "Polyester",
        "Bold",
        "A vivid red rug that makes a loud statement in a living room.",
        ("Vivid red color", "Soft pile", "160 x 230 cm"),
        "prominently red non-neutral color conflicts with the neutral intent",
    ),
)

_BACKPACK: Final = (
    _row(
        "BACKPACK",
        STRONG,
        "H",
        "Apex Gear",
        "Apex Gear Red Weekend Travel Backpack, 28 L",
        "Red",
        "Ripstop nylon",
        "Sport",
        "A red 28-liter travel backpack sized for weekend trips and the gym.",
        ("28 L capacity", "Red ripstop nylon", "Padded laptop sleeve"),
        "red backpack suitable for travel, sport, or weekend carrying",
    ),
    _row(
        "BACKPACK",
        STRONG,
        "G",
        "Apex Gear",
        "Apex Gear Crimson Hiking Daypack, 22 L",
        "Crimson",
        "Nylon",
        "Outdoor",
        "A crimson 22-liter hiking daypack with breathable straps for casual trails.",
        ("22 L capacity", "Crimson nylon shell", "Breathable back panel"),
        "red backpack suitable for travel, sport, or weekend carrying",
    ),
    _row(
        "BACKPACK",
        STRONG,
        "G",
        "Northline",
        "Northline Burgundy Gym Backpack, 25 L",
        "Burgundy",
        "Polyester",
        "Casual",
        "A burgundy gym backpack with a shoe compartment and water-bottle pockets.",
        ("25 L capacity", "Burgundy polyester", "Separate shoe compartment"),
        "red backpack suitable for travel, sport, or weekend carrying",
    ),
    _row(
        "BACKPACK",
        STRONG,
        "S",
        "Northline",
        "Northline Red Overnight Backpack, 30 L",
        "Red",
        "Polyester",
        "Casual",
        "A red 30-liter overnight backpack with a clamshell opening for short trips.",
        ("30 L clamshell opening", "Red polyester body", "Multiple organizer pockets"),
        "red backpack suitable for travel, sport, or weekend carrying",
    ),
    _row(
        "BACKPACK",
        STRONG,
        "S",
        "Haven & Co.",
        "Haven & Co. Maroon Casual Laptop Backpack, 20 L",
        "Maroon",
        "Canvas",
        "Everyday",
        "A maroon canvas backpack with a padded 15-inch laptop sleeve for daily carry.",
        ("Padded 15-inch laptop sleeve", "Maroon canvas", "20 L everyday size"),
        "red backpack suitable for travel, sport, or weekend carrying",
    ),
    _row(
        "BACKPACK",
        STRONG,
        "N",
        "Haven & Co.",
        "Haven & Co. Red Classic Backpack, 24 L",
        "Red",
        "Nylon",
        "Classic",
        "A classic red 24-liter backpack for school, gym, or weekend errands.",
        ("24 L capacity", "Classic red nylon", "Front utility pocket"),
        "red backpack suitable for travel, sport, or weekend carrying",
    ),
    _row(
        "BACKPACK",
        PARTIAL,
        "N",
        "Northline",
        "Northline Black Travel Backpack, 26 L",
        "Black",
        "Polyester",
        "Casual",
        "A black 26-liter travel backpack sized for weekend trips and daily use.",
        ("26 L capacity", "Black polyester", "Laptop compartment"),
        "trip-suitable backpack with an explicit color mismatch (black)",
    ),
    _row(
        "BACKPACK",
        INTRA_TYPE_HARD_NEGATIVE,
        "R",
        "Verdant",
        "Verdant Kids Yellow School Backpack, 12 L",
        "Yellow",
        "Polyester",
        "Kids",
        "A small yellow backpack designed for young children with a sternum clip.",
        ("12 L child size", "Bright yellow", "Reflective trim"),
        "specialized child use and bright yellow conflict with the red weekend intent",
    ),
)

_HEADPHONES: Final = (
    _row(
        "HEADPHONES",
        STRONG,
        "H",
        "Lumora",
        "Lumora On-Ear Wireless Headphones, Charcoal",
        "Charcoal",
        "Plastic and leatherette",
        "Everyday",
        "Wireless on-ear headphones with cushioned pads for everyday music listening.",
        ("On-ear form factor", "Wireless Bluetooth 5.2", "20-hour battery"),
        "explicit on-ear form factor for everyday listening",
    ),
    _row(
        "HEADPHONES",
        STRONG,
        "G",
        "Lumora",
        "Lumora On-Ear Foldable Headphones, Black",
        "Black",
        "Plastic",
        "Portable",
        "Foldable on-ear headphones that collapse flat for commuting and everyday use.",
        ("On-ear cushions", "Foldable frame", "3.5 mm jack included"),
        "explicit on-ear form factor for everyday listening",
    ),
    _row(
        "HEADPHONES",
        STRONG,
        "G",
        "Meridian",
        "Meridian Supra-Aural Wired Headphones, Grey",
        "Grey",
        "Metal and leatherette",
        "Studio",
        "Supra-aural wired headphones with a balanced, everyday listening profile.",
        ("Supra-aural (on-ear) pads", "Braided cable", "Lightweight headband"),
        "explicit on-ear form factor for everyday listening",
    ),
    _row(
        "HEADPHONES",
        STRONG,
        "S",
        "Meridian",
        "Meridian On-Ear Bluetooth Headphones, Navy",
        "Navy",
        "Plastic",
        "Casual",
        "On-ear Bluetooth headphones tuned for daily music and calls.",
        ("On-ear form factor", "Built-in microphone", "Multipoint pairing"),
        "explicit on-ear form factor for everyday listening",
    ),
    _row(
        "HEADPHONES",
        STRONG,
        "S",
        "Cloudrest",
        "Cloudrest On-Ear Cushion Headphones, Beige",
        "Beige",
        "Plastic and foam",
        "Comfort",
        "On-ear headphones with extra-thick cushions for long everyday listening.",
        ("On-ear padded cushions", "Soft-touch finish", "Universal 3.5 mm plug"),
        "explicit on-ear form factor for everyday listening",
    ),
    _row(
        "HEADPHONES",
        STRONG,
        "N",
        "Cloudrest",
        "Cloudrest On-Ear Wired Headphones, White",
        "White",
        "Plastic",
        "Minimal",
        "Minimal white on-ear headphones for straightforward everyday music.",
        ("On-ear form factor", "White finish", "Inline volume control"),
        "explicit on-ear form factor for everyday listening",
    ),
    _row(
        "HEADPHONES",
        PARTIAL,
        "N",
        "Lumora",
        "Lumora Over-Ear Wireless Headphones, Black",
        "Black",
        "Plastic and leatherette",
        "Everyday",
        "Everyday-capable wireless headphones with an over-ear, ear-surrounding design.",
        ("Over-ear cups", "Wireless Bluetooth", "Active noise cancellation"),
        "everyday headphones with an over-ear form-factor mismatch",
    ),
    _row(
        "HEADPHONES",
        INTRA_TYPE_HARD_NEGATIVE,
        "R",
        "Apex Gear",
        "Apex Gear In-Ear Earbuds with Mic, Black",
        "Black",
        "Plastic and silicone",
        "Compact",
        "In-ear earbuds with silicone tips and an inline microphone.",
        ("In-ear silicone tips", "Inline microphone", "Carrying case"),
        "in-ear form factor conflicts with everyday on-ear listening",
    ),
    _row(
        "HEADPHONES",
        INTRA_TYPE_HARD_NEGATIVE,
        "R",
        "Apex Gear",
        "Apex Gear Single-Ear Chat Headset, Black",
        "Black",
        "Plastic",
        "Office",
        "A single-ear USB chat headset intended for call-center use.",
        ("Single-ear design", "USB connection", "Noise-cancelling boom mic"),
        "single-ear chat headset conflicts with everyday on-ear listening",
    ),
)

_UMBRELLA: Final = (
    _row(
        "UMBRELLA",
        STRONG,
        "H",
        "Ironfield",
        "Ironfield Black Automatic Folding Travel Umbrella",
        "Black",
        "Fiberglass and steel",
        "Compact",
        "A black automatic folding umbrella sized to slip into a commuter bag.",
        ("Automatic one-button open", "Black canopy", "Folds to 28 cm"),
        "black automatic folding umbrella suitable for commuting",
    ),
    _row(
        "UMBRELLA",
        STRONG,
        "G",
        "Ironfield",
        "Ironfield Black Wind-Vented Automatic Umbrella",
        "Black",
        "Fiberglass ribs",
        "Durable",
        "A black automatic umbrella with wind vents for stormy commutes.",
        ("Wind-vented canopy", "Automatic open", "Black fabric"),
        "black automatic folding umbrella suitable for commuting",
    ),
    _row(
        "UMBRELLA",
        STRONG,
        "G",
        "Northline",
        "Northline Compact Black Auto Umbrella",
        "Black",
        "Aluminum and polyester",
        "Compact",
        "A compact black automatic umbrella for daily rain commutes.",
        ("Compact folded length", "Automatic open/close", "Black canopy"),
        "black automatic folding umbrella suitable for commuting",
    ),
    _row(
        "UMBRELLA",
        STRONG,
        "S",
        "Northline",
        "Northline Black Foldable Commuter Umbrella",
        "Black",
        "Steel",
        "Classic",
        "A black foldable umbrella with a rubberized grip for wet commutes.",
        ("Foldable shaft", "Black water-repellent canopy", "Rubberized grip"),
        "black automatic folding umbrella suitable for commuting",
    ),
    _row(
        "UMBRELLA",
        STRONG,
        "S",
        "Meridian",
        "Meridian Black Automatic Travel Umbrella",
        "Black",
        "Fiberglass",
        "Travel",
        "A black automatic travel umbrella that fits a briefcase or tote.",
        ("Automatic open", "Black canopy", "Travel size"),
        "black automatic folding umbrella suitable for commuting",
    ),
    _row(
        "UMBRELLA",
        STRONG,
        "N",
        "Meridian",
        "Meridian Black Folding Auto Umbrella",
        "Black",
        "Polyester",
        "Practical",
        "A black folding automatic umbrella for predictable daily coverage.",
        ("Automatic mechanism", "Black polyester canopy", "Wrist strap"),
        "black automatic folding umbrella suitable for commuting",
    ),
    _row(
        "UMBRELLA",
        PARTIAL,
        "N",
        "Northline",
        "Northline Navy Automatic Folding Travel Umbrella",
        "Navy",
        "Fiberglass and steel",
        "Compact",
        "An automatic folding travel umbrella in a deep navy color.",
        ("Automatic open", "Navy canopy", "Compact folded length"),
        "automatic portable umbrella with an explicit non-black color",
    ),
    _row(
        "UMBRELLA",
        INTRA_TYPE_HARD_NEGATIVE,
        "R",
        "Solace Living",
        "Solace Living Oversize Patio Market Umbrella, 2.7 m",
        "Beige",
        "Aluminum",
        "Outdoor",
        "A large patio market umbrella built for garden shade, not commuting.",
        ("2.7 m canopy", "Crank lift", "Weighted base required"),
        "patio/market use conflicts with a commuter umbrella",
    ),
)

_BED: Final = (
    _row(
        "BED",
        STRONG,
        "H",
        "Ironfield",
        "Ironfield Burnished Bronze Bed Frame, Queen",
        "Burnished Bronze",
        "Steel",
        "Modern",
        "A modern queen bed frame with a warm burnished bronze metal finish.",
        ("Burnished bronze finish", "Steel frame", "Queen size"),
        "bronze-family metal finish on a modern bed frame",
    ),
    _row(
        "BED",
        STRONG,
        "G",
        "Ironfield",
        "Ironfield Oiled Bronze Platform Bed, King",
        "Oiled Bronze",
        "Steel",
        "Modern",
        "A king platform bed with an oiled bronze frame for a warm modern bedroom.",
        ("Oiled bronze finish", "Platform base", "King size"),
        "bronze-family metal finish on a modern bed frame",
    ),
    _row(
        "BED",
        STRONG,
        "G",
        "Haven & Co.",
        "Haven & Co. Dark Bronze Bed Frame, Full",
        "Dark Bronze",
        "Steel",
        "Contemporary",
        "A full-size bed frame in a dark bronze metal finish with clean lines.",
        ("Dark bronze finish", "Metal frame", "Full size"),
        "bronze-family metal finish on a modern bed frame",
    ),
    _row(
        "BED",
        STRONG,
        "S",
        "Haven & Co.",
        "Haven & Co. Bronze Metal Bed Frame, Twin",
        "Bronze",
        "Steel",
        "Minimal",
        "A twin bed frame with a bronze metal finish for a compact modern room.",
        ("Bronze finish", "Steel slats", "Twin size"),
        "bronze-family metal finish on a modern bed frame",
    ),
    _row(
        "BED",
        STRONG,
        "S",
        "Meridian",
        "Meridian Warm Bronze Upholstered Bed, Queen",
        "Warm Bronze",
        "Steel and fabric",
        "Modern",
        "A queen bed with a warm bronze metal frame and neutral upholstered panels.",
        ("Warm bronze metal frame", "Neutral fabric panels", "Queen size"),
        "bronze-family metal finish on a modern bed frame",
    ),
    _row(
        "BED",
        STRONG,
        "N",
        "Meridian",
        "Meridian Contemporary Bronze Bed Frame, Full",
        "Bronze",
        "Steel",
        "Contemporary",
        "A contemporary full bed frame with a clean bronze finish.",
        ("Bronze finish", "Contemporary silhouette", "Full size"),
        "bronze-family metal finish on a modern bed frame",
    ),
    _row(
        "BED",
        PARTIAL,
        "N",
        "Ironfield",
        "Ironfield Gold Modern Bed Frame, Queen",
        "Gold",
        "Steel",
        "Modern",
        "A modern queen bed frame with a bright gold metal finish.",
        ("Gold finish", "Steel frame", "Queen size"),
        "gold metal finish conflicts with the requested bronze-family finish",
    ),
    _row(
        "BED",
        INTRA_TYPE_HARD_NEGATIVE,
        "R",
        "Apex Gear",
        "Apex Gear Twin Bunk Bed with Ladder, White",
        "White",
        "Wood",
        "Kids",
        "A white twin bunk bed with a ladder built for children's rooms.",
        ("Twin bunk layout", "Integrated ladder", "White painted wood"),
        "bunk/subtype mismatch conflicts with the modern bed-frame intent",
    ),
)

# ---------------------------------------------------------------------------
# Background types: five to six generic products each, all catalog_background.
# ---------------------------------------------------------------------------

_BACKGROUND: Final = (
    _row(
        "SOFA",
        BACKGROUND,
        "R",
        "Solace Living",
        "Solace Living Navy Three-Seat Sofa",
        "Navy",
        "Fabric",
        "Classic",
        "A three-seat fabric sofa in a deep navy for the living room.",
        ("Three seats", "Navy fabric", "Removable cushions"),
        "background catalog coverage",
    ),
    _row(
        "SOFA",
        BACKGROUND,
        "R",
        "Solace Living",
        "Solace Living Grey Loveseat",
        "Grey",
        "Linen",
        "Casual",
        "A grey two-seat loveseat for smaller living spaces.",
        ("Two seats", "Grey linen", "Wood legs"),
        "background catalog coverage",
    ),
    _row(
        "SOFA",
        BACKGROUND,
        "N",
        "Cloudrest",
        "Cloudrest Beige Sleeper Sofa",
        "Beige",
        "Fabric",
        "Practical",
        "A beige sleeper sofa that converts to a guest bed.",
        ("Converts to bed", "Beige fabric", "Full-size mattress"),
        "background catalog coverage",
    ),
    _row(
        "SOFA",
        BACKGROUND,
        "R",
        "Cloudrest",
        "Cloudrest Charcoal Sectional Sofa",
        "Charcoal",
        "Fabric",
        "Modern",
        "A charcoal sectional sofa for larger living rooms.",
        ("L-shaped sectional", "Charcoal fabric", "Storage ottoman included"),
        "background catalog coverage",
    ),
    _row(
        "SOFA",
        BACKGROUND,
        "R",
        "Haven & Co.",
        "Haven & Co. Brown Leather Sofa",
        "Brown",
        "Faux leather",
        "Classic",
        "A brown faux-leather sofa for a traditional living room.",
        ("Brown faux leather", "Classic arms", "Three seats"),
        "background catalog coverage",
    ),
    _row(
        "CHAIR",
        BACKGROUND,
        "R",
        "Timbermark",
        "Timbermark Oak Dining Chair, Set of 2",
        "Oak",
        "Wood",
        "Classic",
        "A set of two oak dining chairs with upholstered seats.",
        ("Set of two", "Solid oak frame", "Fabric seat"),
        "background catalog coverage",
    ),
    _row(
        "CHAIR",
        BACKGROUND,
        "R",
        "Timbermark",
        "Timbermark Grey Accent Armchair",
        "Grey",
        "Fabric",
        "Modern",
        "A grey accent armchair for a reading corner.",
        ("Accent size", "Grey fabric", "Tapered legs"),
        "background catalog coverage",
    ),
    _row(
        "CHAIR",
        BACKGROUND,
        "N",
        "Meridian",
        "Meridian Ergonomic Office Chair, Black",
        "Black",
        "Mesh",
        "Ergonomic",
        "A black mesh office chair with lumbar support.",
        ("Mesh back", "Adjustable height", "Lumbar support"),
        "background catalog coverage",
    ),
    _row(
        "CHAIR",
        BACKGROUND,
        "R",
        "Meridian",
        "Meridian Beige Swivel Lounge Chair",
        "Beige",
        "Fabric",
        "Contemporary",
        "A beige swivel lounge chair for relaxed seating.",
        ("360-degree swivel", "Beige fabric", "Padded seat"),
        "background catalog coverage",
    ),
    _row(
        "CHAIR",
        BACKGROUND,
        "R",
        "Verdant",
        "Verdant Rattan Accent Chair",
        "Natural",
        "Rattan",
        "Bohemian",
        "A natural rattan accent chair with a curved back.",
        ("Rattan weave", "Curved back", "Lightweight"),
        "background catalog coverage",
    ),
    _row(
        "TABLE",
        BACKGROUND,
        "R",
        "Timbermark",
        "Timbermark Round Oak Coffee Table",
        "Oak",
        "Wood",
        "Classic",
        "A round oak coffee table for the center of a living room.",
        ("Round top", "Oak finish", "Lower shelf"),
        "background catalog coverage",
    ),
    _row(
        "TABLE",
        BACKGROUND,
        "R",
        "Timbermark",
        "Timbermark Glass Side Table, Set of 2",
        "Clear",
        "Glass and metal",
        "Modern",
        "A set of two clear glass side tables with metal frames.",
        ("Set of two", "Tempered glass top", "Metal legs"),
        "background catalog coverage",
    ),
    _row(
        "TABLE",
        BACKGROUND,
        "N",
        "Haven & Co.",
        "Haven & Co. Walnut Console Table",
        "Walnut",
        "Wood",
        "Transitional",
        "A narrow walnut console table for an entryway.",
        ("Narrow profile", "Walnut finish", "One drawer"),
        "background catalog coverage",
    ),
    _row(
        "TABLE",
        BACKGROUND,
        "R",
        "Haven & Co.",
        "Haven & Co. White Dining Table, 4 Seats",
        "White",
        "MDF",
        "Modern",
        "A white four-seat dining table for compact dining areas.",
        ("Four seats", "White finish", "Straight legs"),
        "background catalog coverage",
    ),
    _row(
        "TABLE",
        BACKGROUND,
        "R",
        "Cloudrest",
        "Cloudrest Marble-Effect Dining Table",
        "White and Grey",
        "MDF",
        "Contemporary",
        "A marble-effect dining table with a grey veined top.",
        ("Marble-effect top", "Grey veining", "Seats six"),
        "background catalog coverage",
    ),
    _row(
        "LAMP",
        BACKGROUND,
        "R",
        "Lumora",
        "Lumora Brass Table Lamp",
        "Brass",
        "Metal",
        "Classic",
        "A brass table lamp with a fabric shade for bedside lighting.",
        ("Brass base", "Fabric shade", "Warm light"),
        "background catalog coverage",
    ),
    _row(
        "LAMP",
        BACKGROUND,
        "R",
        "Lumora",
        "Lumora Black Arc Floor Lamp",
        "Black",
        "Steel",
        "Modern",
        "A black arc floor lamp that reaches over a sofa or chair.",
        ("Arc arm", "Black steel", "Marble base"),
        "background catalog coverage",
    ),
    _row(
        "LAMP",
        BACKGROUND,
        "N",
        "Meridian",
        "Meridian White Desk Lamp with USB Port",
        "White",
        "Plastic and metal",
        "Practical",
        "A white desk lamp with a built-in USB charging port.",
        ("Built-in USB port", "Adjustable arm", "White finish"),
        "background catalog coverage",
    ),
    _row(
        "LAMP",
        BACKGROUND,
        "R",
        "Meridian",
        "Meridian Grey Bedside Lamp",
        "Grey",
        "Ceramic",
        "Minimal",
        "A grey ceramic bedside lamp with a linen shade.",
        ("Ceramic base", "Linen shade", "Compact size"),
        "background catalog coverage",
    ),
    _row(
        "LAMP",
        BACKGROUND,
        "R",
        "Cloudrest",
        "Cloudrest Tripod Wood Floor Lamp",
        "Natural",
        "Wood",
        "Bohemian",
        "A natural wood tripod floor lamp for soft ambient light.",
        ("Tripod legs", "Wood finish", "Fabric drum shade"),
        "background catalog coverage",
    ),
    _row(
        "HANDBAG",
        BACKGROUND,
        "R",
        "Verdant",
        "Verdant Tan Leather Tote Bag",
        "Tan",
        "Faux leather",
        "Classic",
        "A tan faux-leather tote with room for a laptop and daily essentials.",
        ("Fits 15-inch laptop", "Tan faux leather", "Interior zip pocket"),
        "background catalog coverage",
    ),
    _row(
        "HANDBAG",
        BACKGROUND,
        "R",
        "Verdant",
        "Verdant Black Crossbody Bag",
        "Black",
        "Nylon",
        "Casual",
        "A black nylon crossbody bag with an adjustable strap.",
        ("Adjustable strap", "Black nylon", "Front zip pocket"),
        "background catalog coverage",
    ),
    _row(
        "HANDBAG",
        BACKGROUND,
        "N",
        "Northline",
        "Northline Olive Canvas Shoulder Bag",
        "Olive",
        "Canvas",
        "Everyday",
        "An olive canvas shoulder bag for everyday carrying.",
        ("Olive canvas", "Magnetic closure", "Inner slip pockets"),
        "background catalog coverage",
    ),
    _row(
        "HANDBAG",
        BACKGROUND,
        "R",
        "Northline",
        "Northline Grey Satchel Bag",
        "Grey",
        "Faux leather",
        "Professional",
        "A grey faux-leather satchel with a structured silhouette.",
        ("Structured shape", "Grey faux leather", "Laptop sleeve"),
        "background catalog coverage",
    ),
    _row(
        "HANDBAG",
        BACKGROUND,
        "R",
        "Haven & Co.",
        "Haven & Co. Navy Hobo Bag",
        "Navy",
        "Fabric",
        "Casual",
        "A navy slouchy hobo bag for relaxed everyday use.",
        ("Slouchy shape", "Navy fabric", "Single shoulder strap"),
        "background catalog coverage",
    ),
    _row(
        "SHOES",
        BACKGROUND,
        "R",
        "Apex Gear",
        "Apex Gear White Leather Sneakers",
        "White",
        "Leather",
        "Casual",
        "White leather sneakers with a cushioned sole for everyday wear.",
        ("White leather upper", "Cushioned insole", "Rubber sole"),
        "background catalog coverage",
    ),
    _row(
        "SHOES",
        BACKGROUND,
        "R",
        "Apex Gear",
        "Apex Gear Black Running Shoes",
        "Black",
        "Mesh",
        "Sport",
        "Black running shoes with a breathable mesh upper.",
        ("Breathable mesh", "Lightweight midsole", "Black finish"),
        "background catalog coverage",
    ),
    _row(
        "SHOES",
        BACKGROUND,
        "N",
        "Northline",
        "Northline Brown Leather Loafers",
        "Brown",
        "Leather",
        "Dress",
        "Brown leather loafers for smart-casual occasions.",
        ("Brown leather", "Slip-on style", "Leather sole"),
        "background catalog coverage",
    ),
    _row(
        "SHOES",
        BACKGROUND,
        "R",
        "Northline",
        "Northline Grey Knit Sneakers",
        "Grey",
        "Knit",
        "Casual",
        "Grey knit sneakers with a sock-like fit.",
        ("Knit upper", "Grey colorway", "Flexible sole"),
        "background catalog coverage",
    ),
    _row(
        "SHOES",
        BACKGROUND,
        "R",
        "Verdant",
        "Verdant Navy Deck Shoes",
        "Navy",
        "Canvas",
        "Boat",
        "Navy canvas deck shoes with non-marking soles.",
        ("Navy canvas", "Non-marking sole", "Slip-on"),
        "background catalog coverage",
    ),
    _row(
        "BOOT",
        BACKGROUND,
        "R",
        "Apex Gear",
        "Apex Gear Brown Hiking Boots",
        "Brown",
        "Leather",
        "Outdoor",
        "Brown leather hiking boots with waterproof treatment.",
        ("Waterproof leather", "Ankle support", "Grippy outsole"),
        "background catalog coverage",
    ),
    _row(
        "BOOT",
        BACKGROUND,
        "R",
        "Apex Gear",
        "Apex Gear Black Work Boots",
        "Black",
        "Leather",
        "Utility",
        "Black leather work boots with a reinforced toe.",
        ("Reinforced toe", "Black leather", "Oil-resistant sole"),
        "background catalog coverage",
    ),
    _row(
        "BOOT",
        BACKGROUND,
        "N",
        "Northline",
        "Northline Tan Chelsea Boots",
        "Tan",
        "Suede",
        "Classic",
        "Tan suede Chelsea boots with elastic side panels.",
        ("Tan suede", "Elastic side panels", "Low heel"),
        "background catalog coverage",
    ),
    _row(
        "BOOT",
        BACKGROUND,
        "R",
        "Northline",
        "Northline Grey Winter Boots",
        "Grey",
        "Synthetic",
        "Winter",
        "Grey insulated winter boots for cold, wet weather.",
        ("Insulated lining", "Water-resistant upper", "Grey finish"),
        "background catalog coverage",
    ),
    _row(
        "BOOT",
        BACKGROUND,
        "R",
        "Verdant",
        "Verdant Brown Desert Boots",
        "Brown",
        "Suede",
        "Casual",
        "Brown suede desert boots with crepe soles.",
        ("Brown suede", "Crepe sole", "Lace-up"),
        "background catalog coverage",
    ),
    _row(
        "SANDAL",
        BACKGROUND,
        "R",
        "Verdant",
        "Verdant Brown Leather Sandals",
        "Brown",
        "Leather",
        "Casual",
        "Brown leather sandals with adjustable straps.",
        ("Brown leather", "Adjustable straps", "Contoured footbed"),
        "background catalog coverage",
    ),
    _row(
        "SANDAL",
        BACKGROUND,
        "R",
        "Verdant",
        "Verdant Black Slide Sandals",
        "Black",
        "EVA",
        "Casual",
        "Black slide sandals with a cushioned EVA footbed.",
        ("Cushioned footbed", "Black EVA", "Easy slip-on"),
        "background catalog coverage",
    ),
    _row(
        "SANDAL",
        BACKGROUND,
        "N",
        "Northline",
        "Northline Tan Sport Sandals",
        "Tan",
        "Synthetic",
        "Sport",
        "Tan sport sandals with hook-and-loop straps for trails.",
        ("Hook-and-loop straps", "Trail-ready sole", "Tan finish"),
        "background catalog coverage",
    ),
    _row(
        "SANDAL",
        BACKGROUND,
        "R",
        "Northline",
        "Northline Navy Thong Sandals",
        "Navy",
        "Rubber",
        "Beach",
        "Navy rubber thong sandals for the beach or pool.",
        ("Navy rubber", "Quick-drying", "Textured footbed"),
        "background catalog coverage",
    ),
    _row(
        "SANDAL",
        BACKGROUND,
        "R",
        "Apex Gear",
        "Apex Gear Grey Walking Sandals",
        "Grey",
        "Mesh",
        "Outdoor",
        "Grey walking sandals with breathable mesh straps.",
        ("Breathable mesh", "Grey colorway", "Adjustable heel"),
        "background catalog coverage",
    ),
    _row(
        "HAT",
        BACKGROUND,
        "R",
        "Verdant",
        "Verdant Beige Straw Sun Hat",
        "Beige",
        "Straw",
        "Summer",
        "A beige straw sun hat with a wide brim.",
        ("Wide brim", "Beige straw", "Inner band"),
        "background catalog coverage",
    ),
    _row(
        "HAT",
        BACKGROUND,
        "R",
        "Verdant",
        "Verdant Navy Baseball Cap",
        "Navy",
        "Cotton",
        "Casual",
        "A navy cotton baseball cap with an adjustable strap.",
        ("Navy cotton", "Adjustable strap", "Curved brim"),
        "background catalog coverage",
    ),
    _row(
        "HAT",
        BACKGROUND,
        "N",
        "Northline",
        "Northline Grey Wool Beanie",
        "Grey",
        "Wool",
        "Winter",
        "A grey wool beanie for cold-weather wear.",
        ("Grey wool", "Ribbed knit", "Fold-over cuff"),
        "background catalog coverage",
    ),
    _row(
        "HAT",
        BACKGROUND,
        "R",
        "Northline",
        "Northline Black Bucket Hat",
        "Black",
        "Cotton",
        "Casual",
        "A black cotton bucket hat with a soft brim.",
        ("Black cotton", "Soft brim", "Packable"),
        "background catalog coverage",
    ),
    _row(
        "HAT",
        BACKGROUND,
        "R",
        "Apex Gear",
        "Apex Gear Olive Wide-Brim Hat",
        "Olive",
        "Nylon",
        "Outdoor",
        "An olive wide-brim hat with a chin strap for sun protection.",
        ("Olive nylon", "Wide brim", "Adjustable chin strap"),
        "background catalog coverage",
    ),
    _row(
        "SUITCASE",
        BACKGROUND,
        "R",
        "Apex Gear",
        "Apex Gear Navy Hardshell Spinner, 20 in",
        "Navy",
        "Polycarbonate",
        "Travel",
        "A 20-inch navy hardshell spinner for carry-on travel.",
        ("20-inch carry-on", "Navy polycarbonate", "Four spinner wheels"),
        "background catalog coverage",
    ),
    _row(
        "SUITCASE",
        BACKGROUND,
        "R",
        "Apex Gear",
        "Apex Gear Black Checked Suitcase, 26 in",
        "Black",
        "Polycarbonate",
        "Travel",
        "A 26-inch black checked suitcase with a TSA lock.",
        ("26-inch checked size", "Black polycarbonate", "TSA lock"),
        "background catalog coverage",
    ),
    _row(
        "SUITCASE",
        BACKGROUND,
        "N",
        "Northline",
        "Northline Grey Softside Spinner, 24 in",
        "Grey",
        "Fabric",
        "Travel",
        "A 24-inch grey softside spinner with expandable capacity.",
        ("Expandable", "Grey fabric", "Four wheels"),
        "background catalog coverage",
    ),
    _row(
        "SUITCASE",
        BACKGROUND,
        "R",
        "Northline",
        "Northline Olive Cabin Bag, 18 in",
        "Olive",
        "Fabric",
        "Travel",
        "An 18-inch olive cabin bag sized for budget airlines.",
        ("18-inch cabin size", "Olive fabric", "Lightweight frame"),
        "background catalog coverage",
    ),
    _row(
        "SUITCASE",
        BACKGROUND,
        "R",
        "Verdant",
        "Verdant Tan Leather Weekend Bag",
        "Tan",
        "Faux leather",
        "Travel",
        "A tan faux-leather weekend bag with a shoulder strap.",
        ("Tan faux leather", "Shoulder strap", "Weekend capacity"),
        "background catalog coverage",
    ),
    _row(
        "DRINKING_CUP",
        BACKGROUND,
        "R",
        "Verdant",
        "Verdant Clear Insulated Tumbler, 20 oz",
        "Clear",
        "Tritan",
        "Everyday",
        "A clear 20-ounce insulated tumbler with a lid and straw.",
        ("20 oz capacity", "Double-wall insulation", "Lid and straw"),
        "background catalog coverage",
    ),
    _row(
        "DRINKING_CUP",
        BACKGROUND,
        "R",
        "Verdant",
        "Verdant Ceramic Coffee Mug, Set of 4",
        "White",
        "Ceramic",
        "Classic",
        "A set of four white ceramic coffee mugs.",
        ("Set of four", "White ceramic", "12 oz capacity"),
        "background catalog coverage",
    ),
    _row(
        "DRINKING_CUP",
        BACKGROUND,
        "N",
        "Northline",
        "Northline Stainless Steel Bottle, 24 oz",
        "Silver",
        "Stainless steel",
        "Active",
        "A 24-ounce stainless steel bottle for hot or cold drinks.",
        ("24 oz capacity", "Insulated steel", "Leakproof lid"),
        "background catalog coverage",
    ),
    _row(
        "DRINKING_CUP",
        BACKGROUND,
        "R",
        "Northline",
        "Northline Navy Sports Water Bottle",
        "Navy",
        "Plastic",
        "Sport",
        "A navy squeeze sports water bottle with a push-pull cap.",
        ("Push-pull cap", "Navy plastic", "28 oz capacity"),
        "background catalog coverage",
    ),
    _row(
        "DRINKING_CUP",
        BACKGROUND,
        "R",
        "Lumora",
        "Lumora Amber Glass Tumblers, Set of 6",
        "Amber",
        "Glass",
        "Retro",
        "A set of six amber glass tumblers for everyday drinks.",
        ("Set of six", "Amber glass", "10 oz capacity"),
        "background catalog coverage",
    ),
    _row(
        "PILLOW",
        BACKGROUND,
        "R",
        "Cloudrest",
        "Cloudrest White Down Pillow, Standard",
        "White",
        "Down fill",
        "Classic",
        "A standard white down pillow with a soft cotton cover.",
        ("Down fill", "White cotton cover", "Standard size"),
        "background catalog coverage",
    ),
    _row(
        "PILLOW",
        BACKGROUND,
        "R",
        "Cloudrest",
        "Cloudrest Grey Memory Foam Pillow",
        "Grey",
        "Memory foam",
        "Support",
        "A grey memory-foam pillow with a cooling gel layer.",
        ("Memory foam", "Cooling gel layer", "Grey cover"),
        "background catalog coverage",
    ),
    _row(
        "PILLOW",
        BACKGROUND,
        "N",
        "Haven & Co.",
        "Haven & Co. Beige Throw Cushions, Set of 2",
        "Beige",
        "Cotton",
        "Casual",
        "A set of two beige cotton throw cushions for a sofa or bed.",
        ("Set of two", "Beige cotton", "Removable covers"),
        "background catalog coverage",
    ),
    _row(
        "PILLOW",
        BACKGROUND,
        "R",
        "Haven & Co.",
        "Haven & Co. Navy Lumbar Cushion",
        "Navy",
        "Linen",
        "Coastal",
        "A navy linen lumbar cushion for lower-back support on a sofa.",
        ("Lumbar shape", "Navy linen", "Hidden zip"),
        "background catalog coverage",
    ),
    _row(
        "PILLOW",
        BACKGROUND,
        "R",
        "Solace Living",
        "Solace Living Sage Decorative Pillow",
        "Sage",
        "Velvet",
        "Modern",
        "A sage velvet decorative pillow with a plush fill.",
        ("Sage velvet", "Plush fill", "45 x 45 cm"),
        "background catalog coverage",
    ),
    _row(
        "SHELF",
        BACKGROUND,
        "R",
        "Timbermark",
        "Timbermark Oak Wall Shelf, 80 cm",
        "Oak",
        "Wood",
        "Classic",
        "An 80-centimeter oak wall shelf for books and decor.",
        ("80 cm width", "Oak finish", "Hidden brackets"),
        "background catalog coverage",
    ),
    _row(
        "SHELF",
        BACKGROUND,
        "R",
        "Timbermark",
        "Timbermark Black Metal Shelving Unit, 5-Tier",
        "Black",
        "Steel",
        "Industrial",
        "A five-tier black steel shelving unit for storage rooms.",
        ("Five tiers", "Black steel", "Adjustable shelves"),
        "background catalog coverage",
    ),
    _row(
        "SHELF",
        BACKGROUND,
        "N",
        "Haven & Co.",
        "Haven & Co. White Cube Shelf, 3-Cube",
        "White",
        "MDF",
        "Modern",
        "A white three-cube shelf that fits standard storage bins.",
        ("Three cubes", "White MDF", "Wall or floor mount"),
        "background catalog coverage",
    ),
    _row(
        "SHELF",
        BACKGROUND,
        "R",
        "Haven & Co.",
        "Haven & Co. Walnut Floating Shelf, 60 cm",
        "Walnut",
        "Wood",
        "Minimal",
        "A 60-centimeter walnut floating shelf with concealed mounts.",
        ("60 cm width", "Walnut finish", "Concealed mounts"),
        "background catalog coverage",
    ),
    _row(
        "SHELF",
        BACKGROUND,
        "R",
        "Meridian",
        "Meridian Grey Corner Shelf, 5-Tier",
        "Grey",
        "MDF",
        "Practical",
        "A grey five-tier corner shelf that uses tight wall space.",
        ("Corner fit", "Five tiers", "Grey finish"),
        "background catalog coverage",
    ),
    _row(
        "PLANTER",
        BACKGROUND,
        "R",
        "Verdant",
        "Verdant Terracotta Plant Pot, 20 cm",
        "Terracotta",
        "Clay",
        "Classic",
        "A 20-centimeter terracotta plant pot with a drainage hole.",
        ("20 cm diameter", "Terracotta clay", "Drainage hole"),
        "background catalog coverage",
    ),
    _row(
        "PLANTER",
        BACKGROUND,
        "R",
        "Verdant",
        "Verdant White Ceramic Planter, Set of 2",
        "White",
        "Ceramic",
        "Modern",
        "A set of two white ceramic planters for indoor plants.",
        ("Set of two", "White ceramic", "Glazed finish"),
        "background catalog coverage",
    ),
    _row(
        "PLANTER",
        BACKGROUND,
        "N",
        "Solace Living",
        "Solace Living Grey Stone Planter, 25 cm",
        "Grey",
        "Stone composite",
        "Minimal",
        "A grey stone-composite planter for a modern interior.",
        ("25 cm diameter", "Stone composite", "Indoor or outdoor"),
        "background catalog coverage",
    ),
    _row(
        "PLANTER",
        BACKGROUND,
        "R",
        "Solace Living",
        "Solace Living Hanging Macrame Planter",
        "Natural",
        "Cotton rope",
        "Bohemian",
        "A hanging cotton-rope planter with a wooden ring.",
        ("Cotton rope", "Hanging design", "Wooden ring"),
        "background catalog coverage",
    ),
    _row(
        "PLANTER",
        BACKGROUND,
        "R",
        "Cloudrest",
        "Cloudrest Self-Watering Window Box, 60 cm",
        "White",
        "Plastic",
        "Practical",
        "A 60-centimeter self-watering window box for herbs or flowers.",
        ("Self-watering", "60 cm width", "White plastic"),
        "background catalog coverage",
    ),
    _row(
        "PLANTER",
        BACKGROUND,
        "R",
        "Cloudrest",
        "Cloudrest Metal Trough Planter, 80 cm",
        "Black",
        "Metal",
        "Industrial",
        "An 80-centimeter black metal trough planter for a patio or balcony.",
        ("80 cm width", "Black metal", "Drainage holes"),
        "background catalog coverage",
    ),
)


# ---------------------------------------------------------------------------
# Expansion pass: six additional catalog_background products per product type.
# Appended after the original 120 rows so the first 120 synthetic IDs, sequences,
# and content bytes are unchanged; these rows only widen the catalog so every
# query's vector Top-20 fills with same-type candidates instead of a single
# cross-category super-item.
# ---------------------------------------------------------------------------

_EXPANSION: Final = (
    _row(
        "DESK",
        BACKGROUND,
        "R",
        "Timbermark",
        "Timbermark Oak Writing Desk, 120 x 60 cm",
        "Oak",
        "Wood",
        "Classic",
        "A classic oak writing desk with a full-size work surface and two drawers.",
        ("120 x 60 cm top", "Oak finish", "Two storage drawers"),
        "background catalog coverage",
    ),
    _row(
        "DESK",
        BACKGROUND,
        "R",
        "Haven & Co.",
        "Haven & Co. Glass-Top Computer Desk, 110 x 55 cm",
        "Clear",
        "Glass and steel",
        "Modern",
        "A modern computer desk with a tempered glass top and a steel frame.",
        ("Tempered glass top", "110 x 55 cm", "Steel frame"),
        "background catalog coverage",
    ),
    _row(
        "DESK",
        BACKGROUND,
        "R",
        "Northline",
        "Northline Crank Standing Desk, 120 x 60 cm",
        "Black",
        "Steel",
        "Adjustable",
        "A black crank-adjustable standing desk for alternating between sit and stand.",
        ("Manual crank height adjustment", "120 x 60 cm top", "Black steel frame"),
        "background catalog coverage",
    ),
    _row(
        "DESK",
        BACKGROUND,
        "R",
        "Meridian",
        "Meridian Pine Study Desk, 100 x 50 cm",
        "Pine",
        "Wood",
        "Traditional",
        "A traditional pine study desk with a lower shelf for books.",
        ("Pine wood finish", "100 x 50 cm top", "Lower shelf"),
        "background catalog coverage",
    ),
    _row(
        "DESK",
        BACKGROUND,
        "R",
        "Cloudrest",
        "Cloudrest Walnut and White Desk, 120 x 55 cm",
        "Walnut and White",
        "MDF",
        "Contemporary",
        "A contemporary two-tone desk with a walnut top and white frame.",
        ("Two-tone walnut and white", "120 x 55 cm top", "Cable management tray"),
        "background catalog coverage",
    ),
    _row(
        "DESK",
        BACKGROUND,
        "R",
        "Apex Gear",
        "Apex Gear Brown Corner Writing Desk, 120 cm",
        "Brown",
        "MDF",
        "Transitional",
        "A brown corner writing desk sized for a compact home office nook.",
        ("Corner fit", "Brown MDF finish", "Keyboard tray"),
        "background catalog coverage",
    ),
    _row(
        "RUG",
        BACKGROUND,
        "R",
        "Cloudrest",
        "Cloudrest Denim Blue Runner Rug, 80 x 200 cm",
        "Blue",
        "Cotton",
        "Casual",
        "A denim blue runner rug for hallways and entryways.",
        ("80 x 200 cm runner", "Blue cotton", "Low pile"),
        "background catalog coverage",
    ),
    _row(
        "RUG",
        BACKGROUND,
        "R",
        "Solace Living",
        "Solace Living Rust Orange Area Rug, 160 x 230 cm",
        "Rust",
        "Polyester",
        "Bohemian",
        "A rust orange area rug with a soft, medium pile for warm rooms.",
        ("Rust orange tone", "160 x 230 cm", "Medium pile"),
        "background catalog coverage",
    ),
    _row(
        "RUG",
        BACKGROUND,
        "R",
        "Haven & Co.",
        "Haven & Co. Charcoal Wool Rug, 140 x 200 cm",
        "Charcoal",
        "Wool",
        "Modern",
        "A charcoal wool rug that hides foot traffic in busy rooms.",
        ("Charcoal neutral", "Natural wool", "140 x 200 cm"),
        "background catalog coverage",
    ),
    _row(
        "RUG",
        BACKGROUND,
        "R",
        "Verdant",
        "Verdant Sage Indoor Rug, 120 x 170 cm",
        "Sage",
        "Cotton blend",
        "Farmhouse",
        "A muted sage cotton-blend rug for a quiet farmhouse interior.",
        ("Sage green tone", "Cotton blend", "120 x 170 cm"),
        "background catalog coverage",
    ),
    _row(
        "RUG",
        BACKGROUND,
        "R",
        "Meridian",
        "Meridian Terracotta Border Rug, 150 x 210 cm",
        "Terracotta",
        "Wool blend",
        "Traditional",
        "A traditional wool-blend rug with a terracotta border pattern.",
        ("Terracotta border", "Wool blend", "150 x 210 cm"),
        "background catalog coverage",
    ),
    _row(
        "RUG",
        BACKGROUND,
        "R",
        "Northline",
        "Northline Navy Striped Rug, 130 x 190 cm",
        "Navy",
        "Jute",
        "Coastal",
        "A navy striped jute rug for a relaxed coastal look.",
        ("Navy stripe pattern", "Natural jute", "130 x 190 cm"),
        "background catalog coverage",
    ),
    _row(
        "BACKPACK",
        BACKGROUND,
        "R",
        "Northline",
        "Northline Grey Commuter Backpack, 22 L",
        "Grey",
        "Polyester",
        "Urban",
        "A grey 22-liter commuter backpack with a padded laptop compartment.",
        ("22 L capacity", "Padded laptop sleeve", "Grey polyester"),
        "background catalog coverage",
    ),
    _row(
        "BACKPACK",
        BACKGROUND,
        "R",
        "Apex Gear",
        "Apex Gear Navy Laptop Backpack, 25 L",
        "Navy",
        "Nylon",
        "Office",
        "A navy 25-liter backpack with organizer pockets for office carry.",
        ("25 L capacity", "Navy nylon", "Organizer panel"),
        "background catalog coverage",
    ),
    _row(
        "BACKPACK",
        BACKGROUND,
        "R",
        "Haven & Co.",
        "Haven & Co. Tan Canvas Rucksack, 20 L",
        "Tan",
        "Canvas",
        "Retro",
        "A tan canvas rucksack with buckle straps for an everyday retro look.",
        ("20 L capacity", "Tan canvas", "Buckle closure"),
        "background catalog coverage",
    ),
    _row(
        "BACKPACK",
        BACKGROUND,
        "R",
        "Verdant",
        "Verdant Green Hiking Pack, 28 L",
        "Green",
        "Ripstop nylon",
        "Outdoor",
        "A green 28-liter hiking pack with a ventilated back panel.",
        ("28 L capacity", "Green ripstop nylon", "Ventilated back"),
        "background catalog coverage",
    ),
    _row(
        "BACKPACK",
        BACKGROUND,
        "R",
        "Cloudrest",
        "Cloudrest Teal Daypack, 18 L",
        "Teal",
        "Polyester",
        "Casual",
        "A teal 18-liter daypack for light daily errands.",
        ("18 L capacity", "Teal polyester", "Water-bottle pockets"),
        "background catalog coverage",
    ),
    _row(
        "BACKPACK",
        BACKGROUND,
        "R",
        "Meridian",
        "Meridian Charcoal Travel Pack, 30 L",
        "Charcoal",
        "Nylon",
        "Travel",
        "A charcoal 30-liter travel pack with a clamshell opening.",
        ("30 L clamshell", "Charcoal nylon", "Compression straps"),
        "background catalog coverage",
    ),
    _row(
        "HEADPHONES",
        BACKGROUND,
        "R",
        "Meridian",
        "Meridian Closed-Back Studio Headphones, Black",
        "Black",
        "Metal and leatherette",
        "Studio",
        "Closed-back studio headphones with a neutral monitoring profile.",
        ("Closed-back cups", "Neutral tuning", "Detachable cable"),
        "background catalog coverage",
    ),
    _row(
        "HEADPHONES",
        BACKGROUND,
        "R",
        "Cloudrest",
        "Cloudrest Wireless Over-Ear Headphones, Grey",
        "Grey",
        "Plastic",
        "Everyday",
        "Wireless over-ear headphones in grey with a soft headband.",
        ("Over-ear cups", "Wireless Bluetooth", "Soft headband"),
        "background catalog coverage",
    ),
    _row(
        "HEADPHONES",
        BACKGROUND,
        "R",
        "Lumora",
        "Lumora Wired Earbuds with Mic, White",
        "White",
        "Plastic",
        "Compact",
        "Wired earbuds with an inline microphone for calls on the go.",
        ("In-ear tips", "Inline microphone", "Tangle-free cable"),
        "background catalog coverage",
    ),
    _row(
        "HEADPHONES",
        BACKGROUND,
        "R",
        "Apex Gear",
        "Apex Gear Kids Headphones, Blue",
        "Blue",
        "Plastic",
        "Kids",
        "Volume-limited kids headphones in blue for safe daily listening.",
        ("Volume limited", "Blue finish", "Adjustable band"),
        "background catalog coverage",
    ),
    _row(
        "HEADPHONES",
        BACKGROUND,
        "R",
        "Northline",
        "Northline Bluetooth Neckband Earphones, Black",
        "Black",
        "Silicone",
        "Sport",
        "Bluetooth neckband earphones with a secure fit for workouts.",
        ("Neckband design", "Bluetooth", "Sweat resistant"),
        "background catalog coverage",
    ),
    _row(
        "HEADPHONES",
        BACKGROUND,
        "R",
        "Haven & Co.",
        "Haven & Co. Folding Over-Ear Headphones, Tan",
        "Tan",
        "Leatherette",
        "Portable",
        "Foldable over-ear headphones in tan for travel and commuting.",
        ("Folding frame", "Tan leatherette", "Travel pouch"),
        "background catalog coverage",
    ),
    _row(
        "UMBRELLA",
        BACKGROUND,
        "R",
        "Northline",
        "Northline Navy Golf Umbrella, 68 in",
        "Navy",
        "Fiberglass",
        "Golf",
        "A large navy golf umbrella with a fiberglass frame and wide canopy.",
        ("68-inch canopy", "Fiberglass ribs", "Navy fabric"),
        "background catalog coverage",
    ),
    _row(
        "UMBRELLA",
        BACKGROUND,
        "R",
        "Solace Living",
        "Solace Living Clear Bubble Umbrella",
        "Clear",
        "Plastic",
        "Fashion",
        "A clear bubble umbrella with a domed canopy for a fashion-forward look.",
        ("Domed canopy", "Clear PVC", "Curved handle"),
        "background catalog coverage",
    ),
    _row(
        "UMBRELLA",
        BACKGROUND,
        "R",
        "Ironfield",
        "Ironfield Red Manual Umbrella",
        "Red",
        "Steel",
        "Classic",
        "A classic red manual umbrella with a steel shaft and wooden handle.",
        ("Red canopy", "Manual open", "Steel shaft"),
        "background catalog coverage",
    ),
    _row(
        "UMBRELLA",
        BACKGROUND,
        "R",
        "Meridian",
        "Meridian Beige Parasol Umbrella, 1.8 m",
        "Beige",
        "Aluminum",
        "Patio",
        "A beige patio parasol for shade over outdoor seating.",
        ("1.8 m canopy", "Aluminum pole", "Tilt mechanism"),
        "background catalog coverage",
    ),
    _row(
        "UMBRELLA",
        BACKGROUND,
        "R",
        "Cloudrest",
        "Cloudrest Kids Umbrella, 50 cm",
        "Yellow",
        "Polyester",
        "Kids",
        "A small yellow kids umbrella with rounded safety tips.",
        ("50 cm canopy", "Yellow polyester", "Rounded tips"),
        "background catalog coverage",
    ),
    _row(
        "UMBRELLA",
        BACKGROUND,
        "R",
        "Haven & Co.",
        "Haven & Co. Wooden-Handle Umbrella",
        "Brown",
        "Wood and polyester",
        "Classic",
        "A classic umbrella with a wooden hook handle and brown canopy.",
        ("Wooden hook handle", "Brown canopy", "Manual frame"),
        "background catalog coverage",
    ),
    _row(
        "BED",
        BACKGROUND,
        "R",
        "Haven & Co.",
        "Haven & Co. Upholstered Platform Bed, Queen",
        "Grey",
        "Fabric",
        "Modern",
        "A grey upholstered queen platform bed with a padded headboard.",
        ("Padded headboard", "Grey fabric", "Queen size"),
        "background catalog coverage",
    ),
    _row(
        "BED",
        BACKGROUND,
        "R",
        "Cloudrest",
        "Cloudrest Wooden Slat Bed, King",
        "Oak",
        "Wood",
        "Scandinavian",
        "A light-oak king bed frame with a slatted base for airflow.",
        ("Oak finish", "Slatted base", "King size"),
        "background catalog coverage",
    ),
    _row(
        "BED",
        BACKGROUND,
        "R",
        "Ironfield",
        "Ironfield Black Metal Bed Frame, Full",
        "Black",
        "Steel",
        "Industrial",
        "A full-size black metal bed frame with clean industrial lines.",
        ("Black steel frame", "Full size", "Easy assembly"),
        "background catalog coverage",
    ),
    _row(
        "BED",
        BACKGROUND,
        "R",
        "Meridian",
        "Meridian Storage Bed with Drawers, Queen",
        "White",
        "MDF",
        "Practical",
        "A white queen bed with under-bed storage drawers for small rooms.",
        ("Two storage drawers", "White MDF", "Queen size"),
        "background catalog coverage",
    ),
    _row(
        "BED",
        BACKGROUND,
        "R",
        "Solace Living",
        "Solace Living Rattan Headboard Bed, Queen",
        "Natural",
        "Rattan",
        "Bohemian",
        "A queen bed with a woven rattan headboard for a bohemian bedroom.",
        ("Rattan headboard", "Queen size", "Natural finish"),
        "background catalog coverage",
    ),
    _row(
        "BED",
        BACKGROUND,
        "R",
        "Northline",
        "Northline Folding Guest Bed, Twin",
        "Blue",
        "Steel",
        "Portable",
        "A folding twin guest bed with a steel frame and thin mattress.",
        ("Folding frame", "Twin size", "Compact storage"),
        "background catalog coverage",
    ),
    _row(
        "SOFA",
        BACKGROUND,
        "R",
        "Solace Living",
        "Solace Living Emerald Velvet Sofa",
        "Emerald",
        "Velvet",
        "Modern",
        "An emerald velvet sofa with brass legs for a statement living room.",
        ("Emerald velvet", "Brass legs", "Three seats"),
        "background catalog coverage",
    ),
    _row(
        "SOFA",
        BACKGROUND,
        "R",
        "Cloudrest",
        "Cloudrest Sand Linen Sofa",
        "Sand",
        "Linen",
        "Coastal",
        "A sand linen sofa with a low profile for a coastal living room.",
        ("Sand linen", "Low profile", "Removable covers"),
        "background catalog coverage",
    ),
    _row(
        "SOFA",
        BACKGROUND,
        "R",
        "Haven & Co.",
        "Haven & Co. Camel Leather Sofa",
        "Camel",
        "Faux leather",
        "Classic",
        "A camel faux-leather sofa for a warm, traditional sitting room.",
        ("Camel faux leather", "Classic arms", "Three seats"),
        "background catalog coverage",
    ),
    _row(
        "SOFA",
        BACKGROUND,
        "R",
        "Timbermark",
        "Timbermark Grey Fabric Sofa Bed",
        "Grey",
        "Fabric",
        "Practical",
        "A grey fabric sofa bed that folds out for overnight guests.",
        ("Converts to bed", "Grey fabric", "Fold-out mattress"),
        "background catalog coverage",
    ),
    _row(
        "SOFA",
        BACKGROUND,
        "R",
        "Verdant",
        "Verdant Olive Velvet Loveseat",
        "Olive",
        "Velvet",
        "Contemporary",
        "An olive velvet loveseat sized for a compact seating area.",
        ("Two seats", "Olive velvet", "Tapered legs"),
        "background catalog coverage",
    ),
    _row(
        "SOFA",
        BACKGROUND,
        "R",
        "Meridian",
        "Meridian White Modular Sofa",
        "White",
        "Fabric",
        "Modern",
        "A white modular sofa that reconfigures for different room layouts.",
        ("Modular sections", "White fabric", "Configurable"),
        "background catalog coverage",
    ),
    _row(
        "CHAIR",
        BACKGROUND,
        "R",
        "Timbermark",
        "Timbermark Walnut Dining Chair",
        "Walnut",
        "Wood",
        "Classic",
        "A walnut dining chair with a contoured seat and slatted back.",
        ("Walnut frame", "Contoured seat", "Slatted back"),
        "background catalog coverage",
    ),
    _row(
        "CHAIR",
        BACKGROUND,
        "R",
        "Meridian",
        "Meridian High-Back Mesh Office Chair, Black",
        "Black",
        "Mesh",
        "Ergonomic",
        "A high-back black mesh office chair with adjustable lumbar support.",
        ("High back", "Mesh fabric", "Adjustable lumbar"),
        "background catalog coverage",
    ),
    _row(
        "CHAIR",
        BACKGROUND,
        "R",
        "Verdant",
        "Verdant Cream Boucle Accent Chair",
        "Cream",
        "Boucle",
        "Modern",
        "A cream boucle accent chair with a rounded silhouette.",
        ("Boucle fabric", "Rounded back", "Cream tone"),
        "background catalog coverage",
    ),
    _row(
        "CHAIR",
        BACKGROUND,
        "R",
        "Cloudrest",
        "Cloudrest Oak Rocking Chair",
        "Oak",
        "Wood",
        "Traditional",
        "An oak rocking chair with a woven seat for a quiet corner.",
        ("Oak frame", "Rocking base", "Woven seat"),
        "background catalog coverage",
    ),
    _row(
        "CHAIR",
        BACKGROUND,
        "R",
        "Haven & Co.",
        "Haven & Co. Brown Leather Lounge Chair",
        "Brown",
        "Leather",
        "Mid-century",
        "A brown leather lounge chair with angled legs and deep cushioning.",
        ("Leather upholstery", "Angled wood legs", "Deep seat"),
        "background catalog coverage",
    ),
    _row(
        "CHAIR",
        BACKGROUND,
        "R",
        "Solace Living",
        "Solace Living Blush Velvet Dining Chairs, Set of 2",
        "Blush",
        "Velvet",
        "Contemporary",
        "A set of two blush velvet dining chairs with gold-tone legs.",
        ("Set of two", "Blush velvet", "Gold-tone legs"),
        "background catalog coverage",
    ),
    _row(
        "TABLE",
        BACKGROUND,
        "R",
        "Timbermark",
        "Timbermark Pine Dining Table, 6 Seats",
        "Pine",
        "Wood",
        "Rustic",
        "A rustic pine dining table that seats six for family meals.",
        ("Seats six", "Pine finish", "Turned legs"),
        "background catalog coverage",
    ),
    _row(
        "TABLE",
        BACKGROUND,
        "R",
        "Haven & Co.",
        "Haven & Co. Round Marble Side Table",
        "White",
        "Marble",
        "Modern",
        "A round white marble side table with a slim pedestal base.",
        ("Marble top", "Pedestal base", "Round shape"),
        "background catalog coverage",
    ),
    _row(
        "TABLE",
        BACKGROUND,
        "R",
        "Cloudrest",
        "Cloudrest Oak Console Table with Drawers",
        "Oak",
        "Wood",
        "Transitional",
        "An oak console table with two drawers for an entryway.",
        ("Oak finish", "Two drawers", "Narrow profile"),
        "background catalog coverage",
    ),
    _row(
        "TABLE",
        BACKGROUND,
        "R",
        "Meridian",
        "Meridian Black Metal Desk Table",
        "Black",
        "Steel",
        "Industrial",
        "A black metal desk table for a simple home workstation.",
        ("Black steel frame", "Wood-look top", "Industrial style"),
        "background catalog coverage",
    ),
    _row(
        "TABLE",
        BACKGROUND,
        "R",
        "Solace Living",
        "Solace Living Nesting Tables, Set of 3",
        "Natural",
        "Wood",
        "Minimal",
        "A set of three natural wood nesting tables that tuck together.",
        ("Set of three", "Natural wood", "Nesting design"),
        "background catalog coverage",
    ),
    _row(
        "TABLE",
        BACKGROUND,
        "R",
        "Verdant",
        "Verdant Oval Glass Coffee Table",
        "Clear",
        "Glass",
        "Contemporary",
        "An oval glass coffee table with a lower display shelf.",
        ("Tempered glass top", "Oval shape", "Lower shelf"),
        "background catalog coverage",
    ),
    _row(
        "LAMP",
        BACKGROUND,
        "R",
        "Lumora",
        "Lumora Cream Ceramic Table Lamp",
        "Cream",
        "Ceramic",
        "Classic",
        "A cream ceramic table lamp with a linen shade for warm bedside light.",
        ("Ceramic base", "Linen shade", "Cream finish"),
        "background catalog coverage",
    ),
    _row(
        "LAMP",
        BACKGROUND,
        "R",
        "Meridian",
        "Meridian Adjustable Reading Lamp, Black",
        "Black",
        "Metal",
        "Task",
        "A black adjustable reading lamp with a focused directional head.",
        ("Adjustable arm", "Directional head", "Black metal"),
        "background catalog coverage",
    ),
    _row(
        "LAMP",
        BACKGROUND,
        "R",
        "Cloudrest",
        "Cloudrest Globe Pendant Lamp",
        "White",
        "Glass",
        "Modern",
        "A white globe pendant lamp for soft overhead dining light.",
        ("Glass globe", "Pendant cord", "White finish"),
        "background catalog coverage",
    ),
    _row(
        "LAMP",
        BACKGROUND,
        "R",
        "Haven & Co.",
        "Haven & Co. Rattan Floor Lamp",
        "Natural",
        "Rattan",
        "Bohemian",
        "A natural rattan floor lamp that casts a warm textured glow.",
        ("Rattan shade", "Floor standing", "Warm light"),
        "background catalog coverage",
    ),
    _row(
        "LAMP",
        BACKGROUND,
        "R",
        "Solace Living",
        "Solace Living Crystal Bedside Lamp",
        "Clear",
        "Crystal",
        "Elegant",
        "A crystal bedside lamp with a faceted base and soft shade.",
        ("Crystal base", "Bedside size", "Fabric shade"),
        "background catalog coverage",
    ),
    _row(
        "LAMP",
        BACKGROUND,
        "R",
        "Verdant",
        "Verdant Green Industrial Desk Lamp",
        "Green",
        "Steel",
        "Industrial",
        "A green industrial desk lamp with a hinged metal arm.",
        ("Hinged arm", "Green steel", "Clamp base"),
        "background catalog coverage",
    ),
    _row(
        "HANDBAG",
        BACKGROUND,
        "R",
        "Verdant",
        "Verdant Black Leather Tote",
        "Black",
        "Leather",
        "Professional",
        "A black leather tote with a zip top for work and daily essentials.",
        ("Fits 15-inch laptop", "Black leather", "Zip top"),
        "background catalog coverage",
    ),
    _row(
        "HANDBAG",
        BACKGROUND,
        "R",
        "Northline",
        "Northline Beige Canvas Tote",
        "Beige",
        "Canvas",
        "Casual",
        "A beige canvas tote with an open top and interior pocket.",
        ("Beige canvas", "Interior pocket", "Shoulder straps"),
        "background catalog coverage",
    ),
    _row(
        "HANDBAG",
        BACKGROUND,
        "R",
        "Haven & Co.",
        "Haven & Co. Red Crossbody Bag",
        "Red",
        "Faux leather",
        "Everyday",
        "A red faux-leather crossbody bag with an adjustable strap.",
        ("Adjustable strap", "Red faux leather", "Front pocket"),
        "background catalog coverage",
    ),
    _row(
        "HANDBAG",
        BACKGROUND,
        "R",
        "Meridian",
        "Meridian Navy Backpack Purse",
        "Navy",
        "Nylon",
        "Practical",
        "A navy backpack purse that converts between backpack and tote.",
        ("Convertible carry", "Navy nylon", "Multiple pockets"),
        "background catalog coverage",
    ),
    _row(
        "HANDBAG",
        BACKGROUND,
        "R",
        "Cloudrest",
        "Cloudrest Brown Woven Handbag",
        "Brown",
        "Straw",
        "Summer",
        "A brown woven straw handbag for warm-weather outfits.",
        ("Woven straw", "Brown tone", "Open top"),
        "background catalog coverage",
    ),
    _row(
        "HANDBAG",
        BACKGROUND,
        "R",
        "Solace Living",
        "Solace Living Grey Quilted Shoulder Bag",
        "Grey",
        "Leather",
        "Classic",
        "A grey quilted shoulder bag with a chain strap.",
        ("Quilted leather", "Chain strap", "Grey tone"),
        "background catalog coverage",
    ),
    _row(
        "SHOES",
        BACKGROUND,
        "R",
        "Apex Gear",
        "Apex Gear Tan Leather Oxfords",
        "Tan",
        "Leather",
        "Dress",
        "Tan leather oxfords with a polished toe for formal wear.",
        ("Tan leather", "Polished toe", "Leather sole"),
        "background catalog coverage",
    ),
    _row(
        "SHOES",
        BACKGROUND,
        "R",
        "Northline",
        "Northline White Canvas Sneakers",
        "White",
        "Canvas",
        "Casual",
        "White canvas sneakers with a vulcanized rubber sole.",
        ("White canvas", "Rubber sole", "Lace-up"),
        "background catalog coverage",
    ),
    _row(
        "SHOES",
        BACKGROUND,
        "R",
        "Verdant",
        "Verdant Black Suede Ankle Boots",
        "Black",
        "Suede",
        "Boot",
        "Black suede ankle boots with a low block heel.",
        ("Suede upper", "Block heel", "Side zip"),
        "background catalog coverage",
    ),
    _row(
        "SHOES",
        BACKGROUND,
        "R",
        "Meridian",
        "Meridian Grey Walking Shoes",
        "Grey",
        "Mesh",
        "Sport",
        "Grey walking shoes with a cushioned midsole for all-day steps.",
        ("Cushioned midsole", "Grey mesh", "Flexible sole"),
        "background catalog coverage",
    ),
    _row(
        "SHOES",
        BACKGROUND,
        "R",
        "Haven & Co.",
        "Haven & Co. Brown Penny Loafers",
        "Brown",
        "Leather",
        "Classic",
        "Brown penny loafers with a classic moc-toe construction.",
        ("Brown leather", "Penny strap", "Slip-on"),
        "background catalog coverage",
    ),
    _row(
        "SHOES",
        BACKGROUND,
        "R",
        "Cloudrest",
        "Cloudrest Navy Boat Shoes",
        "Navy",
        "Canvas",
        "Boat",
        "Navy canvas boat shoes with non-marking rubber soles.",
        ("Navy canvas", "Non-marking sole", "Rawhide laces"),
        "background catalog coverage",
    ),
    _row(
        "BOOT",
        BACKGROUND,
        "R",
        "Apex Gear",
        "Apex Gear Tan Desert Boots",
        "Tan",
        "Suede",
        "Casual",
        "Tan suede desert boots with crepe soles for casual wear.",
        ("Tan suede", "Crepe sole", "Lace-up"),
        "background catalog coverage",
    ),
    _row(
        "BOOT",
        BACKGROUND,
        "R",
        "Northline",
        "Northline Black Chelsea Boots",
        "Black",
        "Leather",
        "Classic",
        "Black leather Chelsea boots with elastic side panels.",
        ("Black leather", "Elastic panels", "Pull tab"),
        "background catalog coverage",
    ),
    _row(
        "BOOT",
        BACKGROUND,
        "R",
        "Verdant",
        "Verdant Brown Steel-Toe Work Boots",
        "Brown",
        "Leather",
        "Utility",
        "Brown leather work boots with a steel toe for job sites.",
        ("Steel toe", "Brown leather", "Slip-resistant sole"),
        "background catalog coverage",
    ),
    _row(
        "BOOT",
        BACKGROUND,
        "R",
        "Meridian",
        "Meridian Grey Rain Boots",
        "Grey",
        "Rubber",
        "Weather",
        "Grey rubber rain boots for wet commutes and puddles.",
        ("Waterproof rubber", "Grey finish", "Pull-on"),
        "background catalog coverage",
    ),
    _row(
        "BOOT",
        BACKGROUND,
        "R",
        "Haven & Co.",
        "Haven & Co. Navy Combat Boots",
        "Navy",
        "Leather",
        "Military",
        "Navy leather combat boots with a lugged sole.",
        ("Navy leather", "Lugged sole", "Lace-up"),
        "background catalog coverage",
    ),
    _row(
        "BOOT",
        BACKGROUND,
        "R",
        "Cloudrest",
        "Cloudrest Taupe Suede Ankle Boots",
        "Taupe",
        "Suede",
        "Fashion",
        "Taupe suede ankle boots with a pointed toe and low heel.",
        ("Taupe suede", "Pointed toe", "Low heel"),
        "background catalog coverage",
    ),
    _row(
        "SANDAL",
        BACKGROUND,
        "R",
        "Verdant",
        "Verdant Tan Leather Slide Sandals",
        "Tan",
        "Leather",
        "Casual",
        "Tan leather slide sandals with a contoured footbed.",
        ("Tan leather", "Contoured footbed", "Slip-on"),
        "background catalog coverage",
    ),
    _row(
        "SANDAL",
        BACKGROUND,
        "R",
        "Northline",
        "Northline Black Flip-Flops",
        "Black",
        "Rubber",
        "Beach",
        "Black rubber flip-flops for the beach or pool.",
        ("Black rubber", "Quick-drying", "Textured sole"),
        "background catalog coverage",
    ),
    _row(
        "SANDAL",
        BACKGROUND,
        "R",
        "Apex Gear",
        "Apex Gear Grey Sport Sandals",
        "Grey",
        "Mesh",
        "Sport",
        "Grey sport sandals with hook-and-loop straps for trails.",
        ("Hook-and-loop straps", "Grey mesh", "Trail sole"),
        "background catalog coverage",
    ),
    _row(
        "SANDAL",
        BACKGROUND,
        "R",
        "Meridian",
        "Meridian White Wedge Sandals",
        "White",
        "Faux leather",
        "Dress",
        "White wedge sandals with an ankle strap for summer outings.",
        ("Wedge heel", "Ankle strap", "White faux leather"),
        "background catalog coverage",
    ),
    _row(
        "SANDAL",
        BACKGROUND,
        "R",
        "Haven & Co.",
        "Haven & Co. Brown Gladiator Sandals",
        "Brown",
        "Leather",
        "Summer",
        "Brown leather gladiator sandals with multiple straps.",
        ("Multi-strap design", "Brown leather", "Flat sole"),
        "background catalog coverage",
    ),
    _row(
        "SANDAL",
        BACKGROUND,
        "R",
        "Cloudrest",
        "Cloudrest Navy Water Sandals",
        "Navy",
        "Neoprene",
        "Outdoor",
        "Navy water sandals with a quick-draining design for kayaking.",
        ("Quick-draining", "Navy neoprene", "Grippy sole"),
        "background catalog coverage",
    ),
    _row(
        "HAT",
        BACKGROUND,
        "R",
        "Verdant",
        "Verdant Grey Wool Fedora",
        "Grey",
        "Wool",
        "Classic",
        "A grey wool fedora with a grosgrain band.",
        ("Wool felt", "Grosgrain band", "Brimmed"),
        "background catalog coverage",
    ),
    _row(
        "HAT",
        BACKGROUND,
        "R",
        "Northline",
        "Northline Black Trucker Cap",
        "Black",
        "Mesh",
        "Casual",
        "A black trucker cap with a mesh back and snap closure.",
        ("Mesh back", "Snap closure", "Black front"),
        "background catalog coverage",
    ),
    _row(
        "HAT",
        BACKGROUND,
        "R",
        "Apex Gear",
        "Apex Gear Tan Boonie Hat",
        "Tan",
        "Cotton",
        "Outdoor",
        "A tan cotton boonie hat with a chin strap for sun protection.",
        ("Tan cotton", "Chin strap", "Wide brim"),
        "background catalog coverage",
    ),
    _row(
        "HAT",
        BACKGROUND,
        "R",
        "Meridian",
        "Meridian Navy Ribbed Beanie",
        "Navy",
        "Acrylic",
        "Winter",
        "A navy ribbed beanie for cold-weather warmth.",
        ("Navy acrylic", "Ribbed knit", "Fold-over cuff"),
        "background catalog coverage",
    ),
    _row(
        "HAT",
        BACKGROUND,
        "R",
        "Haven & Co.",
        "Haven & Co. White Bucket Hat",
        "White",
        "Cotton",
        "Summer",
        "A white cotton bucket hat with a soft brim.",
        ("White cotton", "Soft brim", "Packable"),
        "background catalog coverage",
    ),
    _row(
        "HAT",
        BACKGROUND,
        "R",
        "Cloudrest",
        "Cloudrest Brown Leather Cap",
        "Brown",
        "Leather",
        "Retro",
        "A brown leather cap with a curved brim for a retro look.",
        ("Leather crown", "Curved brim", "Adjustable"),
        "background catalog coverage",
    ),
    _row(
        "SUITCASE",
        BACKGROUND,
        "R",
        "Apex Gear",
        "Apex Gear Grey Hardshell Carry-On, 20 in",
        "Grey",
        "Polycarbonate",
        "Travel",
        "A grey 20-inch hardshell carry-on with four spinner wheels.",
        ("20-inch carry-on", "Grey polycarbonate", "Spinner wheels"),
        "background catalog coverage",
    ),
    _row(
        "SUITCASE",
        BACKGROUND,
        "R",
        "Northline",
        "Northline Navy Duffel Bag, 40 L",
        "Navy",
        "Canvas",
        "Travel",
        "A navy 40-liter canvas duffel for weekend trips and the gym.",
        ("40 L capacity", "Navy canvas", "Shoulder strap"),
        "background catalog coverage",
    ),
    _row(
        "SUITCASE",
        BACKGROUND,
        "R",
        "Verdant",
        "Verdant Tan Leather Duffel, 30 L",
        "Tan",
        "Faux leather",
        "Travel",
        "A tan faux-leather duffel with brass hardware.",
        ("30 L capacity", "Tan faux leather", "Brass hardware"),
        "background catalog coverage",
    ),
    _row(
        "SUITCASE",
        BACKGROUND,
        "R",
        "Meridian",
        "Meridian Black Spinner, 28 in",
        "Black",
        "ABS",
        "Travel",
        "A black 28-inch checked spinner with a combination lock.",
        ("28-inch checked size", "Black ABS", "Combination lock"),
        "background catalog coverage",
    ),
    _row(
        "SUITCASE",
        BACKGROUND,
        "R",
        "Haven & Co.",
        "Haven & Co. Green Cabin Trolley, 18 in",
        "Green",
        "Fabric",
        "Travel",
        "A green 18-inch cabin trolley sized for budget airlines.",
        ("18-inch cabin size", "Green fabric", "Lightweight frame"),
        "background catalog coverage",
    ),
    _row(
        "SUITCASE",
        BACKGROUND,
        "R",
        "Cloudrest",
        "Cloudrest Brown Vintage Trunk, 24 in",
        "Brown",
        "Metal and wood",
        "Travel",
        "A brown vintage-style trunk with metal corners and leather straps.",
        ("Metal corners", "Brown finish", "Leather straps"),
        "background catalog coverage",
    ),
    _row(
        "DRINKING_CUP",
        BACKGROUND,
        "R",
        "Verdant",
        "Verdant Blue Insulated Bottle, 32 oz",
        "Blue",
        "Stainless steel",
        "Active",
        "A blue 32-ounce insulated bottle that keeps drinks cold all day.",
        ("32 oz capacity", "Blue steel", "Vacuum insulation"),
        "background catalog coverage",
    ),
    _row(
        "DRINKING_CUP",
        BACKGROUND,
        "R",
        "Northline",
        "Northline Black Travel Mug, 16 oz",
        "Black",
        "Stainless steel",
        "Travel",
        "A black 16-ounce travel mug with a leak-resistant lid.",
        ("16 oz capacity", "Leak-resistant lid", "Fits cup holders"),
        "background catalog coverage",
    ),
    _row(
        "DRINKING_CUP",
        BACKGROUND,
        "R",
        "Lumora",
        "Lumora Clear Glass Carafe, 1 L",
        "Clear",
        "Glass",
        "Classic",
        "A clear one-liter glass carafe for serving water at the table.",
        ("1 L capacity", "Clear glass", "Narrow neck"),
        "background catalog coverage",
    ),
    _row(
        "DRINKING_CUP",
        BACKGROUND,
        "R",
        "Haven & Co.",
        "Haven & Co. Teal Ceramic Mugs, Set of 2",
        "Teal",
        "Ceramic",
        "Modern",
        "A set of two teal ceramic mugs for everyday coffee.",
        ("Set of two", "Teal ceramic", "14 oz capacity"),
        "background catalog coverage",
    ),
    _row(
        "DRINKING_CUP",
        BACKGROUND,
        "R",
        "Cloudrest",
        "Cloudrest Copper Moscow Mule Mugs, Set of 4",
        "Copper",
        "Metal",
        "Retro",
        "A set of four copper mugs with brass handles for cold drinks.",
        ("Set of four", "Copper finish", "Brass handles"),
        "background catalog coverage",
    ),
    _row(
        "DRINKING_CUP",
        BACKGROUND,
        "R",
        "Meridian",
        "Meridian Grey Tritan Water Bottle, 20 oz",
        "Grey",
        "Tritan",
        "Everyday",
        "A grey 20-ounce Tritan water bottle with a flip-top lid.",
        ("20 oz capacity", "Grey Tritan", "Flip-top lid"),
        "background catalog coverage",
    ),
    _row(
        "PILLOW",
        BACKGROUND,
        "R",
        "Cloudrest",
        "Cloudrest Beige Feather Pillow, Queen",
        "Beige",
        "Feather fill",
        "Classic",
        "A queen beige feather pillow with a soft cotton cover.",
        ("Feather fill", "Queen size", "Cotton cover"),
        "background catalog coverage",
    ),
    _row(
        "PILLOW",
        BACKGROUND,
        "R",
        "Haven & Co.",
        "Haven & Co. Grey Body Pillow",
        "Grey",
        "Memory foam",
        "Support",
        "A grey memory-foam body pillow for side sleepers.",
        ("Memory foam", "Body length", "Grey cover"),
        "background catalog coverage",
    ),
    _row(
        "PILLOW",
        BACKGROUND,
        "R",
        "Solace Living",
        "Solace Living Navy Linen Pillow",
        "Navy",
        "Linen",
        "Coastal",
        "A navy linen decorative pillow for a sofa or bed.",
        ("Navy linen", "Square shape", "Hidden zip"),
        "background catalog coverage",
    ),
    _row(
        "PILLOW",
        BACKGROUND,
        "R",
        "Meridian",
        "Meridian White Cooling Pillow",
        "White",
        "Gel memory foam",
        "Cooling",
        "A white cooling pillow with a gel layer for hot sleepers.",
        ("Cooling gel layer", "White cover", "Standard size"),
        "background catalog coverage",
    ),
    _row(
        "PILLOW",
        BACKGROUND,
        "R",
        "Verdant",
        "Verdant Yellow Throw Pillow",
        "Yellow",
        "Velvet",
        "Accent",
        "A yellow velvet throw pillow that adds a bright accent.",
        ("Yellow velvet", "Plush fill", "45 x 45 cm"),
        "background catalog coverage",
    ),
    _row(
        "PILLOW",
        BACKGROUND,
        "R",
        "Northline",
        "Northline Charcoal Lumbar Pillow",
        "Charcoal",
        "Cotton",
        "Minimal",
        "A charcoal cotton lumbar pillow for lower-back support on a sofa.",
        ("Lumbar shape", "Charcoal cotton", "Removable cover"),
        "background catalog coverage",
    ),
    _row(
        "SHELF",
        BACKGROUND,
        "R",
        "Timbermark",
        "Timbermark Pine Bookcase, 5-Tier",
        "Pine",
        "Wood",
        "Classic",
        "A five-tier pine bookcase for a home library or office.",
        ("Five tiers", "Pine finish", "Adjustable shelves"),
        "background catalog coverage",
    ),
    _row(
        "SHELF",
        BACKGROUND,
        "R",
        "Haven & Co.",
        "Haven & Co. Black Wall Shelves, Set of 3",
        "Black",
        "MDF",
        "Modern",
        "A set of three black wall shelves with hidden brackets.",
        ("Set of three", "Black MDF", "Hidden brackets"),
        "background catalog coverage",
    ),
    _row(
        "SHELF",
        BACKGROUND,
        "R",
        "Meridian",
        "Meridian White Ladder Shelf, 4-Tier",
        "White",
        "Wood",
        "Minimal",
        "A white four-tier ladder shelf that leans against the wall.",
        ("Four tiers", "Ladder design", "White finish"),
        "background catalog coverage",
    ),
    _row(
        "SHELF",
        BACKGROUND,
        "R",
        "Cloudrest",
        "Cloudrest Oak Display Shelf, 90 cm",
        "Oak",
        "Wood",
        "Traditional",
        "A 90-centimeter oak display shelf for collectibles and frames.",
        ("90 cm width", "Oak finish", "Decorative profile"),
        "background catalog coverage",
    ),
    _row(
        "SHELF",
        BACKGROUND,
        "R",
        "Solace Living",
        "Solace Living Bamboo Shelf, 3-Tier",
        "Natural",
        "Bamboo",
        "Eco",
        "A three-tier bamboo shelf for plants and storage.",
        ("Three tiers", "Bamboo material", "Natural finish"),
        "background catalog coverage",
    ),
    _row(
        "SHELF",
        BACKGROUND,
        "R",
        "Verdant",
        "Verdant Grey Floating Shelves, Set of 2",
        "Grey",
        "MDF",
        "Contemporary",
        "A set of two grey floating shelves with concealed mounts.",
        ("Set of two", "Grey MDF", "Concealed mounts"),
        "background catalog coverage",
    ),
    _row(
        "PLANTER",
        BACKGROUND,
        "R",
        "Verdant",
        "Verdant Blue Ceramic Planter, 18 cm",
        "Blue",
        "Ceramic",
        "Modern",
        "An 18-centimeter blue ceramic planter with a drainage hole.",
        ("18 cm diameter", "Blue ceramic", "Drainage hole"),
        "background catalog coverage",
    ),
    _row(
        "PLANTER",
        BACKGROUND,
        "R",
        "Solace Living",
        "Solace Living Terracotta Window Box, 50 cm",
        "Terracotta",
        "Clay",
        "Classic",
        "A 50-centimeter terracotta window box for herbs or flowers.",
        ("50 cm width", "Terracotta clay", "Drainage holes"),
        "background catalog coverage",
    ),
    _row(
        "PLANTER",
        BACKGROUND,
        "R",
        "Cloudrest",
        "Cloudrest White Hanging Planters, Set of 2",
        "White",
        "Ceramic",
        "Minimal",
        "A set of two white ceramic hanging planters with ropes.",
        ("Set of two", "White ceramic", "Hanging ropes"),
        "background catalog coverage",
    ),
    _row(
        "PLANTER",
        BACKGROUND,
        "R",
        "Haven & Co.",
        "Haven & Co. Black Metal Planter, 30 cm",
        "Black",
        "Metal",
        "Industrial",
        "A 30-centimeter black metal planter for a patio or balcony.",
        ("30 cm diameter", "Black metal", "Indoor or outdoor"),
        "background catalog coverage",
    ),
    _row(
        "PLANTER",
        BACKGROUND,
        "R",
        "Northline",
        "Northline Concrete Planter, 22 cm",
        "Grey",
        "Concrete",
        "Modern",
        "A 22-centimeter grey concrete planter with a minimalist look.",
        ("22 cm diameter", "Concrete material", "Grey finish"),
        "background catalog coverage",
    ),
    _row(
        "PLANTER",
        BACKGROUND,
        "R",
        "Meridian",
        "Meridian Rattan Planter Basket, 25 cm",
        "Natural",
        "Rattan",
        "Bohemian",
        "A 25-centimeter rattan planter basket with a liner.",
        ("25 cm diameter", "Rattan weave", "Removable liner"),
        "background catalog coverage",
    ),
)


def build_items() -> list[dict[str, object]]:
    """Assemble the 240-product catalog with stable synthetic IDs and paths."""
    rows = list(
        _DESK + _RUG + _BACKPACK + _HEADPHONES + _UMBRELLA + _BED + _BACKGROUND + _EXPANSION
    )
    items: list[dict[str, object]] = []
    sequence = 0
    seen_ids: set[str] = set()
    for row in rows:
        sequence += 1
        product_type = str(row["product_type"])
        item_id = f"SYN-{product_type}-{sequence:03d}"
        assert item_id not in seen_ids, f"duplicate id {item_id}"
        seen_ids.add(item_id)
        items.append(
            {
                "id": item_id,
                "sequence": sequence,
                "product_type": product_type,
                "selection_class": row["selection_class"],
                "selection_reason": row["selection_reason"],
                "profile": row["profile"],
                "brand": row["brand"],
                "title": row["title"],
                "color": row["color"],
                "material": row["material"],
                "style": row["style"],
                "node_name": f"Catalog > {TYPE_DISPLAY[product_type]}",
                "description": row["description"],
                "bullet_points": list(row["bullet_points"]),
            }
        )
    return items


def validate(items: list[dict[str, object]] | None = None) -> dict[str, object]:
    """Assert catalog quotas and label distribution; return a summary."""
    items = items if items is not None else build_items()
    from function_chain_demo.catalog_curation import (
        SELECTION_LABEL_COUNTS,
        TYPE_ITEM_COUNTS,
    )

    type_counts: dict[str, int] = {}
    label_counts: dict[str, dict[str, int]] = {}
    ids = [str(item["id"]) for item in items]
    assert len(ids) == len(set(ids)), "duplicate ids"
    for item in items:
        product_type = str(item["product_type"])
        label = str(item["selection_class"])
        type_counts[product_type] = type_counts.get(product_type, 0) + 1
        label_counts.setdefault(product_type, {})
        label_counts[product_type][label] = label_counts[product_type].get(label, 0) + 1

    assert len(items) == 240, f"expected 240 items, got {len(items)}"
    assert type_counts == TYPE_ITEM_COUNTS, f"type counts mismatch: {type_counts}"
    for product_type, expected in SELECTION_LABEL_COUNTS.items():
        actual = label_counts.get(product_type, {})
        assert actual.get("strong", 0) == expected["strong"], (product_type, actual)
        assert actual.get("partial", 0) == expected["partial"], (product_type, actual)
        assert actual.get("intra_type_hard_negative", 0) == expected["intra_type_hard_negative"], (
            product_type,
            actual,
        )
    return {
        "items": len(items),
        "unique_ids": len(set(ids)),
        "product_types": len(type_counts),
        "type_counts": type_counts,
        "label_counts": label_counts,
    }


if __name__ == "__main__":
    import json

    summary = validate()
    print(json.dumps(summary, indent=2, sort_keys=True))
